sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
  - osx
      
install:
  - npm install
  

script:
  - npm run --silent travix interp
  - npm run --silent travix neko
  - npm run --silent travix python
  - npm run --silent travix node
  #- npm run --silent travix flash
  - npm run --silent travix java
  - npm run --silent travix cpp
  - npm run --silent travix cs
  - npm run --silent travix php
  - npm run --silent travix lua
  
  
jobs:
  include:
    - stage: deploy
      os: linux
      script: skip
      after_success: npm run --silent travix release

env:
  - secure: "MKc3jIUBhLAa7cQAMnuSJPuYSQrB5WQh1cDsrTGK63NMQHnWNuGHVXeei3PTwrzbK5chT6M4//WKXz090hOK/9HG8ye6ibvgeL0Zp1okYWRpLMQc21JQdFAzsKcT3Vcfc88eNkww3QD9YQvGAJRwJpRfKh/lLIrMRqLEEJ9C8t4="
